services:
  backend:
    container_name: transcribe-translate-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - whisper_models:/app/whisper_models

  frontend:
    container_name: transcribe-translate-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

volumes:
  whisper_models: