services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - whisper_models:/app/whisper_models

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  whisper_models:
