services:
  backend:
    container_name: transcribe-translate-backend
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/whisper_models:/app/whisper_models
  frontend:
    container_name: transcribe-translate-frontend
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  whisper_models:
