name: Deploy Sphinx Documentation

on: 
  push:
    branches:
      - main  # Trigger on pushes to main branch
  pull_request:
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          pip install -r doc/requirements.txt

      - name: Build Sphinx documentation
        run: |
          sphinx-build doc _build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: sphinx-pages  # Separate branch for Sphinx docs
          publish_dir: _build/html      # Directory where Sphinx builds the docs
          force_orphan: true            # Ensures a clean history on the `sphinx-pages` branch
